blank_issues_enabled: false
contact_links:
  - name: Nano Community Forum
    url: https://forum.nano.org
    about: Ask questions and discuss the roadmap here.
  - name: Nano Foundation - Feedback
    url: https://nano.org/connect
    about: Share your feedback with the Nano Foundation.